"use client";

import Link from "next/link";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { ProductArtwork } from "@/components/storefront/product-artwork";
import { useCart } from "@/components/cart/cart-provider";

type Delivery = "nationwide" | "same-day" | "pickup";
type Payment = "maya-online" | "maya-transfer" | "gcash" | "bank" | "cash-pickup" | "";
type Values = { fullName: string; mobile: string; email: string; street: string; province: string; city: string; barangay: string; postal: string; notes: string; delivery: Delivery; payment: Payment; privacy: boolean; terms: boolean; confirmation: boolean };
type FieldName = keyof Values;
const initialValues: Values = { fullName: "", mobile: "", email: "", street: "", province: "", city: "", barangay: "", postal: "", notes: "", delivery: "nationwide", payment: "", privacy: false, terms: false, confirmation: false };
const money = new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", maximumFractionDigits: 0 });
const messengerUrl = "https://www.facebook.com/profile.php?id=100063905416187";
const deliveryLabels: Record<Delivery, string> = { nationwide: "Nationwide Delivery", "same-day": "Same-Day Delivery", pickup: "Store Pickup in Cavite City" };
const paymentLabels: Record<Exclude<Payment, "">, string> = { "maya-online": "Maya Online Payment", "maya-transfer": "Maya Manual Transfer", gcash: "GCash", bank: "Bank Transfer", "cash-pickup": "Cash on Store Pickup" };

function Field({ label, name, value, error, onChange, ...props }: { label: string; name: FieldName; value: string; error?: string; onChange: (name: FieldName, value: string) => void } & Omit<React.InputHTMLAttributes<HTMLInputElement>, "name" | "value" | "onChange">) {
  return <label className="checkout-field" htmlFor={`checkout-${name}`}><span>{label} <b aria-hidden="true">*</b></span><input {...props} aria-describedby={error ? `checkout-${name}-error` : undefined} aria-invalid={!!error} id={`checkout-${name}`} name={name} onChange={(event) => onChange(name, event.target.value)} value={value} />{error ? <small id={`checkout-${name}-error`}>{error}</small> : null}</label>;
}

export function CheckoutForm() {
  const { items, subtotal } = useCart();
  const [values, setValues] = useState(initialValues);
  const [errors, setErrors] = useState<Partial<Record<FieldName, string>>>({});
  const [reviewed, setReviewed] = useState(false);
  const [guidance, setGuidance] = useState("");
  const previousCartRef = useRef("");
  const formRef = useRef<HTMLFormElement>(null);
  const orderLineItems = items.map((item) => ({
    productSlug: item.product.slug,
    sku: item.product.sku,
    quantity: item.quantity,
  }));
  const cartSignature = orderLineItems
    .map((item) => `${item.productSlug}:${item.sku}:${item.quantity}`)
    .join("|");
  useEffect(() => { if (previousCartRef.current && previousCartRef.current !== cartSignature && reviewed) { setReviewed(false); setGuidance("Your cart changed. Review your checkout details again."); } previousCartRef.current = cartSignature; }, [cartSignature, reviewed]);
  if (!items.length) return <section className="checkout-empty"><p className="type-eyebrow text-[var(--color-action)]">CHECKOUT PREVIEW</p><h1>Your checkout is waiting for a cart.</h1><p>Add a GadgetMoTo phone or tablet before continuing to checkout.</p><div><Link href="/shop">Shop All Products</Link><Link href="/phones">Browse Phones</Link><Link href="/tablets">Browse Tablets</Link></div></section>;

  const update = (name: FieldName, value: string | boolean) => { setValues((current) => ({ ...current, [name]: value })); setErrors((current) => ({ ...current, [name]: undefined })); setReviewed(false); };
  const chooseDelivery = (delivery: Delivery) => { setValues((current) => ({ ...current, delivery, payment: delivery !== "pickup" && current.payment === "cash-pickup" ? "" : current.payment })); if (delivery !== "pickup" && values.payment === "cash-pickup") setGuidance("Cash on Store Pickup was cleared because it is available only for store-pickup orders."); setErrors((current) => ({ ...current, delivery: undefined, payment: undefined })); setReviewed(false); };
  const validate = () => {
    const next: Partial<Record<FieldName, string>> = {};
    if (values.fullName.trim().length < 2) next.fullName = "Enter your full name.";
    const mobile = values.mobile.replace(/\D/g, ""); if (!/^(09\d{9}|639\d{9})$/.test(mobile)) next.mobile = "Enter a Philippine mobile number such as 09XXXXXXXXX or +639XXXXXXXXX.";
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email.trim())) next.email = "Enter a valid email address.";
    if (values.delivery !== "pickup") { if (!values.street.trim()) next.street = "Enter the complete street address."; if (!values.province.trim()) next.province = "Enter the province."; if (!values.city.trim()) next.city = "Enter the city or municipality."; if (!values.barangay.trim()) next.barangay = "Enter the barangay."; if (!/^\d{4}$/.test(values.postal.trim())) next.postal = "Enter a valid four-digit postal code."; }
    if (!values.payment) next.payment = "Choose a payment method.";
    if (!values.privacy) next.privacy = "Privacy Policy agreement is required."; if (!values.terms) next.terms = "Terms and Conditions agreement is required."; if (!values.confirmation) next.confirmation = "Confirmation acknowledgement is required.";
    return next;
  };
  const submit = (event: FormEvent) => { event.preventDefault(); const next = validate(); setErrors(next); if (Object.keys(next).length) { setReviewed(false); window.setTimeout(() => formRef.current?.querySelector<HTMLElement>("[aria-invalid='true']")?.focus(), 0); return; } setReviewed(true); setGuidance(""); window.setTimeout(() => document.getElementById("checkout-review")?.focus(), 0); };
  const address = `${values.street}, ${values.barangay}, ${values.city}, ${values.province} ${values.postal}`;

  return <><div className="checkout-heading"><p className="type-eyebrow text-[var(--color-action)]">GUEST CHECKOUT</p><h1>Review your GadgetMoTo order.</h1><p>Checkout preview only. No order or payment will be created.</p></div>{guidance ? <p aria-live="polite" className="checkout-guidance">{guidance}</p> : null}{Object.keys(errors).length ? <aside className="checkout-error-summary" role="alert"><h2>Review the highlighted checkout details.</h2><p>{Object.keys(errors).length} required {Object.keys(errors).length === 1 ? "detail needs" : "details need"} attention.</p></aside> : null}<form className="checkout-grid" noValidate onSubmit={submit} ref={formRef}><div className="checkout-form-sections"><section className="checkout-section"><h2>1. Contact Information</h2><div className="checkout-field-grid"><Field autoComplete="name" error={errors.fullName} label="Full name" name="fullName" onChange={update} value={values.fullName} /><Field autoComplete="tel" error={errors.mobile} inputMode="tel" label="Mobile number" name="mobile" onChange={update} type="tel" value={values.mobile} /><Field autoComplete="email" error={errors.email} label="Email address" name="email" onChange={update} type="email" value={values.email} /></div></section>
  <section className="checkout-section"><fieldset><legend>2. Delivery Method</legend><div className="checkout-options">{(["nationwide","same-day","pickup"] as Delivery[]).map((method) => <label key={method}><input checked={values.delivery === method} name="delivery" onChange={() => chooseDelivery(method)} type="radio" value={method} /><span><strong>{deliveryLabels[method]}</strong><small>{method === "nationwide" ? "Delivery fees, courier details, and timing will be confirmed after review." : method === "same-day" ? "Subject to location, availability, and sales-team confirmation." : "Exact location and pickup schedule will be confirmed by the sales team."}</small></span></label>)}</div></fieldset></section>
  {values.delivery !== "pickup" ? <section className="checkout-section"><h2>3. Delivery Address</h2><div className="checkout-field-grid"><Field autoComplete="street-address" error={errors.street} label="Complete street address" name="street" onChange={update} value={values.street} /><Field autoComplete="address-level1" error={errors.province} label="Province" name="province" onChange={update} value={values.province} /><Field autoComplete="address-level2" error={errors.city} label="City or municipality" name="city" onChange={update} value={values.city} /><Field error={errors.barangay} label="Barangay" name="barangay" onChange={update} value={values.barangay} /><Field autoComplete="postal-code" error={errors.postal} inputMode="numeric" label="Postal code" maxLength={4} name="postal" onChange={update} value={values.postal} /></div></section> : <section className="checkout-section"><h2>3. Store Pickup</h2><p>The exact Cavite City pickup location and schedule will be confirmed by the GadgetMoTo sales team.</p></section>}
  <section className="checkout-section"><fieldset><legend>4. Payment Method</legend><div className="checkout-options">{(["maya-online","maya-transfer","gcash","bank","cash-pickup"] as Exclude<Payment,"">[]).map((method) => <label className={method === "cash-pickup" && values.delivery !== "pickup" ? "checkout-option--disabled" : ""} key={method}><input checked={values.payment === method} disabled={method === "cash-pickup" && values.delivery !== "pickup"} name="payment" onChange={() => update("payment", method)} type="radio" value={method} /><span><strong>{paymentLabels[method]}</strong><small>{method === "maya-online" ? "Secure Maya checkout integration will be connected in a later payment phase." : method === "cash-pickup" ? "Available only for confirmed store-pickup orders." : "Payment details will be provided only after the order is reviewed and confirmed."}</small></span></label>)}</div>{errors.payment ? <small className="checkout-group-error">{errors.payment}</small> : null}</fieldset></section>
  <section className="checkout-section"><h2>5. Order Notes</h2><label className="checkout-field" htmlFor="checkout-notes"><span>Order notes <i>Optional</i></span><textarea id="checkout-notes" maxLength={500} onChange={(event) => update("notes", event.target.value)} rows={4} value={values.notes} /><small className="checkout-help">Add a delivery instruction or question for the GadgetMoTo sales team. Do not include passwords, card details, or other sensitive payment information. {values.notes.length}/500</small></label></section>
  <section className="checkout-section"><fieldset><legend>6. Required Confirmations</legend><div className="checkout-consents"><label><input aria-invalid={!!errors.privacy} checked={values.privacy} onChange={(event) => update("privacy", event.target.checked)} type="checkbox" />I have read and agree to the <Link href="/privacy-policy">Privacy Policy</Link>.</label>{errors.privacy ? <small>{errors.privacy}</small> : null}<label><input aria-invalid={!!errors.terms} checked={values.terms} onChange={(event) => update("terms", event.target.checked)} type="checkbox" />I have read and agree to the <Link href="/terms-and-conditions">Terms and Conditions</Link>.</label>{errors.terms ? <small>{errors.terms}</small> : null}<label><input aria-invalid={!!errors.confirmation} checked={values.confirmation} onChange={(event) => update("confirmation", event.target.checked)} type="checkbox" />I understand that product availability, VAT, delivery fees, pickup details, and final payment instructions must still be confirmed before payment.</label>{errors.confirmation ? <small>{errors.confirmation}</small> : null}</div></fieldset></section><button className="checkout-review-button" type="submit">Review Order — checkout preview</button></div>
  <aside className="checkout-summary"><h2>Order Summary</h2>{items.map((item) => <article key={item.lineId}><div><ProductArtwork product={item.product} sizes="3.5rem" /></div><span><small>{item.product.brand}</small><strong>{item.product.name}</strong><small>{item.variant} · Qty {item.quantity}</small></span><span>{money.format(item.lineTotal)}<small>{money.format(item.product.currentPrice)} each</small></span></article>)}<dl><div><dt>Current merchandise subtotal</dt><dd>{money.format(subtotal)}</dd></div><div><dt>VAT</dt><dd>Pending confirmation</dd></div><div><dt>Shipping or delivery fee</dt><dd>Pending confirmation</dd></div><div><dt>Final payable amount</dt><dd>Pending final VAT, delivery, availability, and payment review</dd></div></dl></aside></form>
  {reviewed ? <section aria-live="polite" className="checkout-review" id="checkout-review" tabIndex={-1}><p className="type-eyebrow">CHECKOUT PREVIEW READY</p><h2>Review only — nothing has been submitted.</h2><strong>Checkout preview only. No order has been created and no payment has been processed.</strong><div className="checkout-review-grid"><section><h3>Customer</h3><p>{values.fullName}<br />{values.mobile}<br />{values.email}</p></section><section><h3>Delivery</h3><p>{deliveryLabels[values.delivery]}<br />{values.delivery === "pickup" ? "Pickup details pending sales-team confirmation." : address}</p></section><section><h3>Payment</h3><p>{values.payment ? paymentLabels[values.payment] : "Not selected"}<br />Preview choice only. No payment has been authorized.</p></section><section><h3>Items</h3>{items.map((item) => <p key={item.lineId}>{item.product.name} · {item.variant} · Qty {item.quantity} · {money.format(item.lineTotal)}</p>)}</section></div><dl><div><dt>Current merchandise subtotal</dt><dd>{money.format(subtotal)}</dd></div><div><dt>VAT</dt><dd>Pending confirmation</dd></div><div><dt>Shipping or delivery fee</dt><dd>Pending confirmation</dd></div><div><dt>Final payable amount</dt><dd>Pending final VAT, delivery, availability, and payment review</dd></div></dl><div><button onClick={() => { setReviewed(false); formRef.current?.querySelector<HTMLElement>("input")?.focus(); }} type="button">Edit Checkout Details</button><a href={messengerUrl} rel="noopener noreferrer" target="_blank">Message GadgetMoTo</a></div></section> : null}</>;
}
