import type { Metadata } from "next";
import { Container } from "@/components/ui/container";
import { StorefrontPageShell } from "@/components/storefront/storefront-page-shell";
export const metadata: Metadata = {
  title: "Privacy Policy Draft | GadgetMoTo",
  description: "Read the pre-launch GadgetMoTo privacy policy draft.",
  alternates: { canonical: "/privacy-policy" },
};
export default function PrivacyPolicyPage() { return <StorefrontPageShell><Container className="storefront-container policy-page py-[var(--space-section)]"><p className="type-eyebrow text-[var(--color-action)]">PRE-LAUNCH DRAFT · BUSINESS AND LEGAL REVIEW REQUIRED</p><h1>Privacy Policy</h1><p>This cautious draft describes the planned checkout-information workflow. Online order submission and backend storage are currently disabled.</p><h2>Information supplied through checkout</h2><p>Checkout fields remain available to help a customer review an order inquiry. The website does not submit those personal details while online ordering is disabled.</p><h2>Planned uses</h2><p>After the business approves final policies and enables ordering, supplied information may be used to review orders, contact customers, and coordinate delivery and payment.</p><h2>Current contact path</h2><p>GadgetMoTo currently handles order inquiries through Facebook Messenger. The checkout contact summary includes cart items, estimated subtotal, and delivery preference only; customers deliberately decide what to send.</p><p>This policy requires final business and legal review before launch. It does not claim unconfirmed certifications, retention periods, or legal guarantees.</p><a href="https://www.facebook.com/profile.php?id=100063905416187" rel="noopener noreferrer" target="_blank">Contact GadgetMoTo through Facebook Messenger</a></Container></StorefrontPageShell>; }
